server:
  port: 8080

spring:
  r2dbc:
    url: r2dbc:mysql://database-1.cdq66ue08ijs.us-east-1.rds.amazonaws.com/franquiciadb
    username: admin
    password: admin1234
  sql:
    init:
      mode: never

appDescription: "MicroServicio Franquicias"
appVersion: "1.0.0"
